Repository aerospike/spring-data-aerospike, pull requests merged in 2022-03, with the labels that each got.

#357 fix circular dependency for AerospikePersistenceEntityIndexCreator
  pom.xml
  src/main/java/org/springframework/data/aerospike/config/AbstractAerospikeDataConfiguration.java
  src/main/java/org/springframework/data/aerospike/config/AbstractReactiveAerospikeDataConfiguration.java
  src/main/java/org/springframework/data/aerospike/config/AerospikeDataConfigurationSupport.java
  src/main/java/org/springframework/data/aerospike/config/AerospikeDataSettings.java
  src/main/java/org/springframework/data/aerospike/index/AerospikePersistenceEntityIndexCreator.java
  src/main/java/org/springframework/data/aerospike/index/BaseAerospikePersistenceEntityIndexCreator.java
  src/main/java/org/springframework/data/aerospike/index/ReactiveAerospikePersistenceEntityIndexCreator.java
  src/main/java/org/springframework/data/aerospike/mapping/AerospikeMappingContext.java
  src/test/java/org/springframework/data/aerospike/index/AerospikePersistenceEntityIndexCreatorTest.java
  src/test/java/org/springframework/data/aerospike/index/ReactiveAerospikePersistenceEntityIndexCreatorTest.java
  src/test/resources/logback-test.xml
Labels: bug

#359 Prepare for version 3.4.0.
  README.md
  pom.xml
Labels: dependencies, documentation

#360 Configure dependabot for Github Actions
  .github/dependabot.yml
Labels: chore
