Repository aerospike/spring-data-aerospike, pull requests merged in 2022-10, with the labels that each got.

#430 Change "record" variable names to "aeroRecord" (Java 14 compatibility)
  src/main/java/org/springframework/data/aerospike/cache/AerospikeCache.java
  src/main/java/org/springframework/data/aerospike/convert/AerospikeReadData.java
  src/main/java/org/springframework/data/aerospike/convert/MappingAerospikeReadConverter.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeKeyValueAdapter.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/BaseAerospikeTemplate.java
  src/test/java/org/springframework/data/aerospike/convert/BaseMappingAerospikeConverterTest.java
  src/test/java/org/springframework/data/aerospike/convert/MappingAerospikeConverterDeprecatedTest.java
  src/test/java/org/springframework/data/aerospike/convert/MappingAerospikeConverterTest.java
  src/test/java/org/springframework/data/aerospike/convert/MappingAerospikeConverterTypesTest.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateSaveTests.java
Labels: chore

#431 Update GitHub actions versions
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/required-labels.yml
Labels: chore

#426 Clean code and update embedded-aerospike to 2.2.8
  pom.xml
  src/main/java/org/springframework/data/aerospike/convert/AerospikeWriteData.java
  src/main/java/org/springframework/data/aerospike/convert/MappingAerospikeReadConverter.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/mapping/AerospikeMappingContext.java
  src/main/java/org/springframework/data/aerospike/query/FilterExpressionsBuilder.java
  src/main/java/org/springframework/data/aerospike/query/Qualifier.java
  src/main/java/org/springframework/data/aerospike/repository/AerospikeRepository.java
  src/test/java/org/springframework/data/aerospike/AsyncUtils.java
  src/test/java/org/springframework/data/aerospike/SampleClasses.java
  src/test/java/org/springframework/data/aerospike/convert/MappingAerospikeConverterDeprecatedTest.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateDeleteRelatedTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateSaveRelatedTests.java
  src/test/java/org/springframework/data/aerospike/index/AerospikePersistenceEntityIndexCreatorTest.java
  src/test/java/org/springframework/data/aerospike/index/ReactiveAerospikePersistenceEntityIndexCreatorTest.java
  src/test/java/org/springframework/data/aerospike/mapping/AerospikePersistentEntityTest.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveIndexedQualifierTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveQualifierTests.java
Labels: enhancement

#414 FMWK-42 Bump Aerospike clients to 6.1.2 and test native char type support
  pom.xml
  src/main/java/org/springframework/data/aerospike/query/cache/IndexInfoParser.java
  src/test/java/org/springframework/data/aerospike/AdditionalAerospikeTestOperations.java
  src/test/java/org/springframework/data/aerospike/IndexUtils.java
  src/test/java/org/springframework/data/aerospike/SampleClasses.java
  src/test/java/org/springframework/data/aerospike/convert/MappingAerospikeConverterTypesTest.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateIndexTests.java
  src/test/java/org/springframework/data/aerospike/core/AutoIndexedDocumentAssert.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateIndexTests.java
  src/test/java/org/springframework/data/aerospike/query/BaseQueryEngineTests.java
  src/test/java/org/springframework/data/aerospike/query/IndexedQualifierTests.java
  src/test/java/org/springframework/data/aerospike/query/cache/IndexTests.java
  src/test/java/org/springframework/data/aerospike/repository/CustomerRepositoriesIntegrationTests.java
  src/test/java/org/springframework/data/aerospike/repository/IndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/reactive/ReactiveAerospikeRepositoryFindRelatedTests.java
  src/test/java/org/springframework/data/aerospike/sample/Customer.java
  src/test/java/org/springframework/data/aerospike/sample/CustomerRepository.java
  src/test/java/org/springframework/data/aerospike/sample/ReactiveCustomerRepository.java
  src/test/resources/bootstrap.properties
Labels: enhancement

#423 FMWK-45 Update specific fields support
  src/main/java/org/springframework/data/aerospike/convert/AerospikeWriteData.java
  src/main/java/org/springframework/data/aerospike/convert/MappingAerospikeWriteConverter.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/BaseAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeTemplate.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateUpdateTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateUpdateTests.java
Labels: enhancement

#433 FMWK-28 Add CTX Support for Secondary Index
  src/main/java/org/springframework/data/aerospike/annotation/Indexed.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/index/AerospikePersistenceEntityIndexCreator.java
  src/main/java/org/springframework/data/aerospike/query/cache/IndexInfoParser.java
  src/main/java/org/springframework/data/aerospike/query/cache/InternalIndexOperations.java
  src/main/java/org/springframework/data/aerospike/query/model/Index.java
  src/test/java/org/springframework/data/aerospike/IndexUtils.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateIndexTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateIndexTests.java
Labels: enhancement

#415 FMWK-43 Projections (The ability to fetch only required fields from Aerospike)
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/mapping/AerospikePersistentProperty.java
  src/main/java/org/springframework/data/aerospike/query/QueryEngine.java
  src/main/java/org/springframework/data/aerospike/query/ReactorQueryEngine.java
  src/main/java/org/springframework/data/aerospike/query/StatementBuilder.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/ReactiveAerospikePartTreeQuery.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryProjectionTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindProjectionTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryProjectionTest.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindProjectionTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/reactive/ReactiveAerospikeRepositoryFindRelatedTests.java
  src/test/java/org/springframework/data/aerospike/sample/Customer.java
  src/test/java/org/springframework/data/aerospike/sample/CustomerSomeFields.java
  src/test/java/org/springframework/data/aerospike/sample/Person.java
  src/test/java/org/springframework/data/aerospike/sample/PersonMissingAndRedundantFields.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
  src/test/java/org/springframework/data/aerospike/sample/PersonSomeFields.java
  src/test/java/org/springframework/data/aerospike/sample/PersonTouchOnRead.java
  src/test/java/org/springframework/data/aerospike/sample/ReactiveCustomerRepository.java
Labels: enhancement

#429 FMWK-54 Implement find by POJO field using comparison operators
  src/main/java/org/springframework/data/aerospike/query/Qualifier.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeCriteria.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/Person.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
Labels: enhancement

#435 FMWK-58 Bump Spring related dependencies to 2.7.
  pom.xml
  src/test/java/org/springframework/data/aerospike/core/AbstractFindByEntitiesTest.java
Labels: dependencies

#437 FMWK-52 Query Aggregations
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateQueryAggregationTests.java
  src/test/resources/udf/average_example.lua
  src/test/resources/udf/sum_example.lua
Labels: enhancement, breaking change

#434 FMWK-55 Supporting Map and List filtering (integer only), refactoring Qualifier, AerospikeCriteria, AerospikeQueryCreator
  src/main/java/org/springframework/data/aerospike/query/ExpiryQualifier.java
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/main/java/org/springframework/data/aerospike/query/KeyQualifier.java
  src/main/java/org/springframework/data/aerospike/query/LatestUpdateQualifier.java
  src/main/java/org/springframework/data/aerospike/query/Qualifier.java
  src/main/java/org/springframework/data/aerospike/query/StatementBuilder.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeCriteria.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/main/java/org/springframework/data/aerospike/repository/query/Criteria.java
  src/test/java/org/springframework/data/aerospike/QueryUtils.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateCountTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateInsertTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateUpdateTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateCountRelatedTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateInsertTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateUpdateTests.java
  src/test/java/org/springframework/data/aerospike/query/IndexedQualifierTests.java
  src/test/java/org/springframework/data/aerospike/query/QualifierTests.java
  src/test/java/org/springframework/data/aerospike/query/UsersTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveIndexedQualifierTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveQualifierTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveSelectorTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveUsersTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonTestData.java
  src/test/java/org/springframework/data/aerospike/sample/IndexedPerson.java
  src/test/java/org/springframework/data/aerospike/sample/Person.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
Labels: enhancement

#442 FMWK-69 Fix condition timeout and improve tests
  pom.xml
  src/test/java/org/springframework/data/aerospike/AdditionalAerospikeTestOperations.java
  src/test/java/org/springframework/data/aerospike/BaseReactiveIntegrationTests.java
  src/test/java/org/springframework/data/aerospike/BlockingAerospikeTestOperations.java
  src/test/java/org/springframework/data/aerospike/ReactiveBlockingAerospikeTestOperations.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateCountTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateExistsTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryProjectionTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateQueryAggregationTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateCountRelatedTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryProjectionTest.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/query/QualifierTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveQualifierTests.java
  src/test/java/org/springframework/data/aerospike/repository/IndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/reactive/ReactiveAerospikeRepositoryFindRelatedTests.java
Labels: bug

#443 correctly setting ignoreCase in AerospikeQueryCreator
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
Labels: bug

#444 FMWK-51 Unsupported find with sort operations
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/BaseAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/repository/support/SimpleAerospikeRepository.java
  src/test/java/org/springframework/data/aerospike/core/AbstractFindByEntitiesTest.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/CustomerRepositoriesIntegrationTests.java
  src/test/java/org/springframework/data/aerospike/repository/reactive/ReactiveAerospikeRepositoryDeleteRelatedTests.java
  src/test/java/org/springframework/data/aerospike/repository/reactive/ReactiveAerospikeRepositoryExistRelatedTests.java
  src/test/java/org/springframework/data/aerospike/repository/reactive/ReactiveAerospikeRepositoryFindRelatedTests.java
  src/test/java/org/springframework/data/aerospike/repository/reactive/ReactiveAerospikeRepositorySaveRelatedTests.java
  src/test/java/org/springframework/data/aerospike/repository/support/SimpleAerospikeRepositoryTest.java
  src/test/java/org/springframework/data/aerospike/repository/support/SimpleReactiveAerospikeRepositoryTest.java
  src/test/java/org/springframework/data/aerospike/sample/Customer.java
  src/test/java/org/springframework/data/aerospike/sample/CustomerRepository.java
  src/test/java/org/springframework/data/aerospike/sample/CustomerSomeFields.java
  src/test/java/org/springframework/data/aerospike/sample/ReactiveCustomerRepository.java
Labels: enhancement

#448 FMWK-56 Additional Queries With Secondary Index
  src/main/java/org/springframework/data/aerospike/query/FilterExpressionsBuilder.java
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/main/java/org/springframework/data/aerospike/query/QueryEngine.java
  src/main/java/org/springframework/data/aerospike/query/StatementBuilder.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryProjectionTest.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/query/QualifierTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveIndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveQualifierTests.java
  src/test/java/org/springframework/data/aerospike/repository/IndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonTestData.java
  src/test/java/org/springframework/data/aerospike/sample/IndexedPerson.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
  src/test/java/org/springframework/data/aerospike/sample/ReactiveIndexedPersonRepository.java
Labels: enhancement

#449 Prepare 3.5.0
  README.md
  pom.xml
Labels: documentation
