Repository aerospike/spring-data-aerospike, pull requests merged in 2023-08, with the labels that each got.

#608 FMWK-210 Add support for MatchesRegex keyword
  src/main/asciidoc/reference/query-methods.adoc
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
Labels: enhancement

#610 FMWK-211 Update java client to 7.0.0
  pom.xml
  src/main/java/org/springframework/data/aerospike/convert/AerospikeWriteData.java
  src/main/java/org/springframework/data/aerospike/convert/MappingAerospikeConverter.java
  src/main/java/org/springframework/data/aerospike/convert/MappingAerospikeWriteConverter.java
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/test/java/org/springframework/data/aerospike/AdditionalAerospikeTestOperations.java
  src/test/java/org/springframework/data/aerospike/query/QueryEngineTestDataPopulator.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreatorUnitTests.java
Labels: enhancement, dependencies

#612 FMWK-202 Add documentation page for Indexed annotation
  README.adoc
  src/main/asciidoc/index.adoc
  src/main/asciidoc/reference/indexed-annotation.adoc
  src/main/asciidoc/reference/secondary-indexes.adoc
  src/test/java/org/springframework/data/aerospike/index/IndexedAnnotationTests.java
Labels: documentation

#614 FMWK-224 Add support for id projection query via Repository
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/query/Qualifier.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/BaseAerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/Query.java
  src/main/java/org/springframework/data/aerospike/repository/query/ReactiveAerospikePartTreeQuery.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
Labels: enhancement

#615 FMWK-223 Update dependencies and version number
  README.adoc
  pom.xml
  src/main/asciidoc/index.adoc
  src/main/asciidoc/reference/aerospike.adoc
  src/main/asciidoc/reference/getting-started.adoc
  src/main/asciidoc/reference/indexed-annotation.adoc
Labels: dependencies

#616 FMWK-226 Update compatibility table
  README.adoc
  src/main/asciidoc/reference/aerospike.adoc
Labels: documentation

#617 FMWK-225 Add support for "findByIdAnd..." queries
  src/main/java/org/springframework/data/aerospike/convert/MappingAerospikeWriteConverter.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeInternalOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/BaseAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeInternalOperations.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/WritePolicyBuilder.java
  src/main/java/org/springframework/data/aerospike/query/QueryEngine.java
  src/main/java/org/springframework/data/aerospike/query/ReactorQueryEngine.java
  src/main/java/org/springframework/data/aerospike/repository/config/BaseAerospikeRepositoryConfigurationExtension.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/BaseAerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/ReactiveAerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/support/AerospikeRepositoryFactory.java
  src/main/java/org/springframework/data/aerospike/repository/support/AerospikeRepositoryFactoryBean.java
  src/main/java/org/springframework/data/aerospike/repository/support/ReactiveAerospikeRepositoryFactory.java
  src/main/java/org/springframework/data/aerospike/repository/support/ReactiveAerospikeRepositoryFactoryBean.java
  src/test/java/org/springframework/data/aerospike/SampleClasses.java
  src/test/java/org/springframework/data/aerospike/convert/MappingAerospikeConverterTypesTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateCountTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateDeleteTests.java
  src/test/java/org/springframework/data/aerospike/repository/IndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/support/AerospikeRepositoryFactoryTest.java
  src/test/java/org/springframework/data/aerospike/repository/support/ReactiveAerospikeRepositoryFactoryTest.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
Labels: enhancement

#619 FMWK-231 Prepare release version 4.5.0
  README.adoc
  pom.xml
  src/main/asciidoc/index.adoc
  src/main/asciidoc/reference/aerospike.adoc
  src/main/asciidoc/reference/getting-started.adoc
Labels: dependencies

#623 FMWK-172 Replace the use of Lazy annotation with ObjectProvider
  src/main/java/org/springframework/data/aerospike/config/AbstractAerospikeDataConfiguration.java
  src/main/java/org/springframework/data/aerospike/config/AbstractReactiveAerospikeDataConfiguration.java
  src/main/java/org/springframework/data/aerospike/config/AerospikeDataConfigurationSupport.java
  src/main/java/org/springframework/data/aerospike/index/AerospikePersistenceEntityIndexCreator.java
  src/main/java/org/springframework/data/aerospike/index/ReactiveAerospikePersistenceEntityIndexCreator.java
  src/test/java/org/springframework/data/aerospike/index/AerospikePersistenceEntityIndexCreatorTest.java
  src/test/java/org/springframework/data/aerospike/index/ReactiveAerospikePersistenceEntityIndexCreatorTest.java
  src/test/java/org/springframework/data/aerospike/utility/MockObjectProvider.java
Labels: enhancement

#622 FMWK-236 Find correct fieldName for queries with Field annotation
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
Labels: bug
