Repository aerospike/spring-data-aerospike, pull requests merged in 2023-06, with the labels that each got.

#571 FMWK-188 Indexed annotation support
  src/main/java/org/springframework/data/aerospike/annotation/Indexed.java
  src/main/java/org/springframework/data/aerospike/index/AerospikeIndexDefinition.java
  src/main/java/org/springframework/data/aerospike/index/AerospikeIndexResolver.java
  src/main/java/org/springframework/data/aerospike/index/AerospikePersistenceEntityIndexCreator.java
  src/main/java/org/springframework/data/aerospike/index/ReactiveAerospikePersistenceEntityIndexCreator.java
  src/main/java/org/springframework/data/aerospike/query/StatementBuilder.java
  src/main/java/org/springframework/data/aerospike/query/model/IndexesInfo.java
  src/test/java/org/springframework/data/aerospike/SampleClasses.java
  src/test/java/org/springframework/data/aerospike/convert/MappingAerospikeConverterTypesTests.java
  src/test/java/org/springframework/data/aerospike/core/AutoIndexedDocumentAssert.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateIndexTests.java
  src/test/java/org/springframework/data/aerospike/index/AerospikePersistenceEntityIndexCreatorTest.java
  src/test/java/org/springframework/data/aerospike/index/IndexedAnnotationTests.java
  src/test/java/org/springframework/data/aerospike/index/ReactiveAerospikePersistenceEntityIndexCreatorTest.java
  src/test/java/org/springframework/data/aerospike/repository/IndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
Labels: enhancement

#578 FMWK-190 Support for String, List, Map in Filter operations
  pom.xml
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/main/java/org/springframework/data/aerospike/query/Qualifier.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/query/QualifierTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveIndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveQualifierTests.java
  src/test/java/org/springframework/data/aerospike/repository/IndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/Person.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
  src/test/java/org/springframework/data/aerospike/sample/ReactiveIndexedPersonRepository.java
Labels: enhancement

#582 FMWK-175 Add "is null bin" condition to NOTEQ filter expression
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
Labels: enhancement

#551 FMWK-169 Add Snyk scan workflow
  .github/workflows/snyk-scan.yml
Labels: chore, github_actions

#584 FMWK-177 Add support for BOOL ParticleType
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryProjectionTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateInsertTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateInsertTests.java
  src/test/java/org/springframework/data/aerospike/repository/IndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/IndexedPerson.java
  src/test/java/org/springframework/data/aerospike/sample/Person.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
Labels: enhancement

#585 FMWK-165 Add GitHub Pages documentation workflow
  .github/workflows/asciidoctor-ghpages.yml
Labels: chore, github_actions

#586 FMWK-164 Documentation Update
  README.adoc
  README.md
  pom.xml
  src/main/asciidoc/index.adoc
  src/main/asciidoc/preface.adoc
  src/main/asciidoc/reference/aerospike-reactive-repositories.adoc
  src/main/asciidoc/reference/aerospike-repositories.adoc
  src/main/asciidoc/reference/aerospike.adoc
  src/main/asciidoc/reference/caching.adoc
  src/main/asciidoc/reference/getting-started.adoc
  src/main/asciidoc/reference/introduction.adoc
  src/main/asciidoc/reference/mapping.adoc
  src/main/asciidoc/reference/projections.adoc
  src/main/asciidoc/reference/query-methods.adoc
  src/main/asciidoc/reference/scan-operation.adoc
  src/main/asciidoc/reference/secondary-indexes.adoc
  src/main/asciidoc/reference/template.adoc
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryTests.java
Labels: documentation

#587 FMWK-191 Make findByList compare only upper level when a Collection is given
  src/main/asciidoc/preface.adoc
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveIndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/IndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
  src/test/java/org/springframework/data/aerospike/sample/ReactiveIndexedPersonRepository.java
Labels: enhancement

#588 FMWK-178 Add support for "Not Containing" queries
  src/main/asciidoc/preface.adoc
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/main/java/org/springframework/data/aerospike/query/Qualifier.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
Labels: enhancement

#589 FMWK-180 Add support for "Not in" queries
  src/main/asciidoc/reference/query-methods.adoc
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
Labels: enhancement

#595 FMWK-160 Add support for "findByFirst/Top"
  src/main/asciidoc/reference/query-methods.adoc
  src/main/java/org/springframework/data/aerospike/repository/query/BaseAerospikePartTreeQuery.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
Labels: enhancement

#597 FMWK-159 Add support for returning Slice
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikePartTreeQuery.java
  src/test/java/org/springframework/data/aerospike/repository/IndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
Labels: enhancement

#599 FMWK-200 Provide compatibility with Aerospike Server EE version
  src/main/java/org/springframework/data/aerospike/convert/MappingAerospikeConverter.java
  src/main/java/org/springframework/data/aerospike/convert/MappingAerospikeWriteConverter.java
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
Labels: enhancement

#596 FMWK-198 Update dependencies versions
  README.adoc
  pom.xml
  src/main/asciidoc/index.adoc
  src/main/asciidoc/preface.adoc
  src/main/asciidoc/reference/aerospike.adoc
  src/main/asciidoc/reference/getting-started.adoc
  src/test/java/org/springframework/data/aerospike/repository/query/StubParameterAccessor.java
Labels: dependencies
