Repository aerospike/spring-data-aerospike, pull requests merged in 2023-12, with the labels that each got.

#660 FMWK-79 Support native Aerospike Key types (false by default)
  src/main/java/org/springframework/data/aerospike/config/AerospikeDataConfigurationSupport.java
  src/main/java/org/springframework/data/aerospike/config/AerospikeDataSettings.java
  src/main/java/org/springframework/data/aerospike/convert/AerospikeConverter.java
  src/main/java/org/springframework/data/aerospike/convert/MappingAerospikeConverter.java
  src/main/java/org/springframework/data/aerospike/convert/MappingAerospikeWriteConverter.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/BaseAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/CoreUtils.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/TemplateUtils.java
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/main/java/org/springframework/data/aerospike/query/Qualifier.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/main/java/org/springframework/data/aerospike/repository/query/BaseAerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/ReactiveAerospikePartTreeQuery.java
  src/test/java/org/springframework/data/aerospike/assertions/KeyAssert.java
  src/test/java/org/springframework/data/aerospike/config/BlockingTestConfig.java
  src/test/java/org/springframework/data/aerospike/config/ReactiveTestConfig.java
  src/test/java/org/springframework/data/aerospike/convert/BaseMappingAerospikeConverterTest.java
  src/test/java/org/springframework/data/aerospike/convert/MappingAerospikeConverterTests.java
  src/test/java/org/springframework/data/aerospike/convert/MappingAerospikeConverterTypesTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeExpirationTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateCompositeKeyTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateDeleteTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByIdTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateInsertTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplatePersistTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateSaveTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateUpdateTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateCompositeKeyTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateDeleteRelatedTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByIdTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateInsertTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateSaveRelatedTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateUpdateTests.java
  src/test/java/org/springframework/data/aerospike/logging/LoggingTests.java
  src/test/java/org/springframework/data/aerospike/mapping/AerospikePersistentEntityTest.java
  src/test/java/org/springframework/data/aerospike/mapping/BasicAerospikePersistentEntityTest.java
  src/test/java/org/springframework/data/aerospike/repository/IdTypesRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreatorUnitTests.java
  src/test/java/org/springframework/data/aerospike/sample/DocumentByteArrayIdRepository.java
  src/test/java/org/springframework/data/aerospike/sample/DocumentByteIdRepository.java
  src/test/java/org/springframework/data/aerospike/sample/DocumentCharacterIdRepository.java
  src/test/java/org/springframework/data/aerospike/sample/DocumentIntegerIdRepository.java
  src/test/java/org/springframework/data/aerospike/sample/DocumentLongIdRepository.java
  src/test/java/org/springframework/data/aerospike/sample/DocumentShortIdRepository.java
  src/test/java/org/springframework/data/aerospike/sample/DocumentStringIdRepository.java
  src/test/java/org/springframework/data/aerospike/sample/Person.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
  src/test/java/org/springframework/data/aerospike/sample/SampleClasses.java
  src/test/java/org/springframework/data/aerospike/utility/QueryUtils.java
  src/test/java/org/springframework/data/aerospike/utility/TimeUtilsTest.java
Labels: enhancement, feature

#661 FMWK-263 Update documentation
  README.adoc
  src/main/asciidoc/index.adoc
  src/main/asciidoc/preface.adoc
  src/main/asciidoc/reference/aerospike-object-mapping.adoc
  src/main/asciidoc/reference/aerospike-repositories.adoc
  src/main/asciidoc/reference/aerospike.adoc
  src/main/asciidoc/reference/configure-data-settings.adoc
  src/main/asciidoc/reference/functionality.adoc
  src/main/asciidoc/reference/getting-started.adoc
  src/main/asciidoc/reference/indexed-annotation.adoc
  src/main/asciidoc/reference/installation-and-usage.adoc
  src/main/asciidoc/reference/introduction.adoc
  src/main/asciidoc/reference/query-methods.adoc
  src/main/asciidoc/reference/scan-operation.adoc
  src/main/asciidoc/reference/secondary-indexes.adoc
  src/main/asciidoc/reference/template.adoc
  src/main/asciidoc/spring-data-commons-docs/object-mapping.adoc
  src/main/asciidoc/spring-data-commons-docs/repositories.adoc
  src/main/java/org/springframework/data/aerospike/annotation/Indexed.java
  src/main/java/org/springframework/data/aerospike/config/AerospikeDataSettings.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeOperations.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateDeleteTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByIdTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateInsertTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateSaveTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateUpdateTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateDeleteRelatedTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateSaveRelatedTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateUpdateTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveIndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
  src/test/java/org/springframework/data/aerospike/sample/SampleClasses.java
Labels: documentation

#677 FMWK-287 Map Key/Value Not Containing Fix
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateCountRelatedTests.java
  src/test/java/org/springframework/data/aerospike/repository/IndexedPersonRepositoryQueryTests.java
Labels: bug

#676 FMWK-284 Integration test for reading data written with Aerospike Java client
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeOperations.java
  src/test/java/org/springframework/data/aerospike/convert/AerospikeReadDataIntegrationTests.java
Labels: enhancement

#666 FMWK-265 Prepare release 4.6.0
  .github/workflows/asciidoctor-ghpages.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/snyk-scan.yml
  README.adoc
  pom.xml
  src/main/asciidoc/reference/aerospike.adoc
  src/main/asciidoc/reference/getting-started.adoc
  src/main/java/org/springframework/data/aerospike/repository/query/Query.java
Labels: dependencies

#681 FMWK-285 Compare versions when performing delete operations
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/BaseAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/repository/support/SimpleAerospikeRepository.java
  src/main/java/org/springframework/data/aerospike/repository/support/SimpleReactiveAerospikeRepository.java
  src/main/java/org/springframework/data/aerospike/utility/Utils.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateDeleteTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateInsertTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateSaveTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateUpdateTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateDeleteRelatedTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateSaveRelatedTests.java
  src/test/java/org/springframework/data/aerospike/repository/support/SimpleAerospikeRepositoryTest.java
  src/test/java/org/springframework/data/aerospike/repository/support/SimpleReactiveAerospikeRepositoryTest.java
  src/test/java/org/springframework/data/aerospike/utility/IndexUtils.java
Labels: enhancement

#682 FMWK-301 Support beforeLastUpdate parameter in deleteAll
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/BaseAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeTemplate.java
  src/test/java/org/springframework/data/aerospike/BaseBlockingIntegrationTests.java
  src/test/java/org/springframework/data/aerospike/BaseIntegrationTests.java
  src/test/java/org/springframework/data/aerospike/BaseReactiveIntegrationTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateDeleteTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateDeleteRelatedTests.java
  src/test/java/org/springframework/data/aerospike/utility/AwaitilityUtils.java
Labels: enhancement
