Repository aerospike/spring-data-aerospike, pull requests merged in 2023-11, with the labels that each got.

#649 FMWK-259 Add converters for commonly used Java types
  pom.xml
  src/main/java/org/springframework/data/aerospike/convert/AerospikeConverters.java
  src/main/java/org/springframework/data/aerospike/convert/DateConverters.java
  src/test/java/org/springframework/data/aerospike/SampleClasses.java
  src/test/java/org/springframework/data/aerospike/convert/MappingAerospikeConverterTypesTests.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateSaveTests.java
Labels: enhancement

#651 FMWK-258 Refactor Operations/Template
  README.adoc
  src/main/java/org/springframework/data/aerospike/core/AerospikeInternalOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeInternalOperations.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/query/KeyQualifier.java
  src/main/java/org/springframework/data/aerospike/query/Qualifier.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/main/java/org/springframework/data/aerospike/repository/query/ReactiveAerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/support/SimpleAerospikeRepository.java
  src/main/java/org/springframework/data/aerospike/repository/support/SimpleReactiveAerospikeRepository.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
Labels: enhancement, documentation

#653 FMWK-182 Event Loop Types in Tests
  pom.xml
  src/test/java/org/springframework/data/aerospike/config/ReactiveTestConfig.java
Labels: enhancement

#652 FMWK-261 Align find APIs to use Query instead of Qualifier
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/TemplateUtils.java
  src/main/java/org/springframework/data/aerospike/query/FilterExpressionsBuilder.java
  src/main/java/org/springframework/data/aerospike/query/KeyQualifier.java
  src/main/java/org/springframework/data/aerospike/query/Qualifier.java
  src/main/java/org/springframework/data/aerospike/query/QualifierUtils.java
  src/main/java/org/springframework/data/aerospike/query/QueryEngine.java
  src/main/java/org/springframework/data/aerospike/query/ReactorQueryEngine.java
  src/main/java/org/springframework/data/aerospike/query/StatementBuilder.java
  src/main/java/org/springframework/data/aerospike/repository/AerospikeRepository.java
  src/main/java/org/springframework/data/aerospike/repository/ReactiveAerospikeRepository.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeCriteria.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/BaseAerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/Query.java
  src/main/java/org/springframework/data/aerospike/repository/query/ReactiveAerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/support/SimpleAerospikeRepository.java
  src/main/java/org/springframework/data/aerospike/repository/support/SimpleReactiveAerospikeRepository.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryProjectionTest.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/logging/LoggingTests.java
  src/test/java/org/springframework/data/aerospike/query/IndexedQualifierTests.java
  src/test/java/org/springframework/data/aerospike/query/QualifierTests.java
  src/test/java/org/springframework/data/aerospike/query/UsersTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveIndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveIndexedQualifierTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveQualifierTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveSelectorTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveUsersTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
Labels: enhancement

#657 FMWK-196 Index Cardinality
  src/main/java/org/springframework/data/aerospike/query/StatementBuilder.java
  src/main/java/org/springframework/data/aerospike/query/cache/IndexRefresher.java
  src/main/java/org/springframework/data/aerospike/query/cache/IndexesCache.java
  src/main/java/org/springframework/data/aerospike/query/cache/IndexesCacheHolder.java
  src/main/java/org/springframework/data/aerospike/query/cache/InternalIndexOperations.java
  src/main/java/org/springframework/data/aerospike/query/cache/ReactorIndexRefresher.java
  src/main/java/org/springframework/data/aerospike/query/model/Index.java
  src/main/java/org/springframework/data/aerospike/utility/ServerVersionUtils.java
Labels: enhancement, feature

#658 FMWK-199 Refactor implementation of paginated queries
  src/main/java/org/springframework/data/aerospike/config/AbstractAerospikeDataConfiguration.java
  src/main/java/org/springframework/data/aerospike/config/AbstractReactiveAerospikeDataConfiguration.java
  src/main/java/org/springframework/data/aerospike/config/AerospikeDataSettings.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/CoreUtils.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeOperations.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/TemplateUtils.java
  src/main/java/org/springframework/data/aerospike/query/FilterExpressionsBuilder.java
  src/main/java/org/springframework/data/aerospike/query/QualifierUtils.java
  src/main/java/org/springframework/data/aerospike/query/QueryEngine.java
  src/main/java/org/springframework/data/aerospike/query/ReactorQueryEngine.java
  src/main/java/org/springframework/data/aerospike/query/StatementBuilder.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/BaseAerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/Query.java
  src/main/java/org/springframework/data/aerospike/repository/query/ReactiveAerospikePartTreeQuery.java
  src/test/java/org/springframework/data/aerospike/config/BlockingTestConfig.java
  src/test/java/org/springframework/data/aerospike/config/ReactiveTestConfig.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateCountTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateCountRelatedTests.java
  src/test/java/org/springframework/data/aerospike/query/reactive/ReactiveIndexedPersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/repository/PersonRepositoryQueryTests.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
  src/test/java/org/springframework/data/aerospike/sample/ReactiveIndexedPersonRepository.java
Labels: enhancement

#659 FMWK-262 Replace AerospikeCriteria with CriteriaDefinition
  src/main/asciidoc/reference/template.adoc
  src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/core/CoreUtils.java
  src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeTemplate.java
  src/main/java/org/springframework/data/aerospike/query/FilterExpressionsBuilder.java
  src/main/java/org/springframework/data/aerospike/query/QueryEngine.java
  src/main/java/org/springframework/data/aerospike/query/ReactorQueryEngine.java
  src/main/java/org/springframework/data/aerospike/query/StatementBuilder.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeCriteria.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreator.java
  src/main/java/org/springframework/data/aerospike/repository/query/BaseAerospikePartTreeQuery.java
  src/main/java/org/springframework/data/aerospike/repository/query/Query.java
  src/main/java/org/springframework/data/aerospike/repository/query/ReactiveAerospikePartTreeQuery.java
  src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateCountTests.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateCountRelatedTests.java
Labels: enhancement
