Repository aerospike/spring-data-aerospike, pull requests merged in 2025-01, with the labels that each got.

#814 FMWK-635 Use correct sIndex filter in containing queries with nested map values
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/main/java/org/springframework/data/aerospike/repository/query/AerospikeQueryCreatorUtils.java
  src/test/java/org/springframework/data/aerospike/core/sync/AerospikeTemplateQueryAggregationTests.java
  src/test/java/org/springframework/data/aerospike/repository/query/blocking/find/ContainingTests.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
Labels: bug

#815 FMWK-636 Use internal flag in Map keys containing queries
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/main/java/org/springframework/data/aerospike/query/qualifier/BaseQualifierBuilder.java
  src/main/java/org/springframework/data/aerospike/query/qualifier/QualifierKey.java
  src/main/java/org/springframework/data/aerospike/repository/query/MapQueryCreator.java
  src/main/java/org/springframework/data/aerospike/repository/query/QueryQualifierBuilder.java
Labels: enhancement

#816 FMWK-346 Use reactive MRT operations
  pom.xml
  src/main/java/org/springframework/data/aerospike/transaction/reactive/AerospikeReactiveTransaction.java
  src/main/java/org/springframework/data/aerospike/transaction/reactive/AerospikeReactiveTransactionManager.java
  src/main/java/org/springframework/data/aerospike/transaction/sync/AerospikeTransactionManager.java
Labels: enhancement

#817 FMWK-634 Apply expression filter as secondary index filter fallback
  src/main/java/org/springframework/data/aerospike/query/QueryEngine.java
  src/main/java/org/springframework/data/aerospike/query/ReactorQueryEngine.java
  src/main/java/org/springframework/data/aerospike/query/StatementBuilder.java
  src/test/java/org/springframework/data/aerospike/core/reactive/ReactiveAerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/core/sync/AerospikeTemplateFindByQueryTests.java
  src/test/java/org/springframework/data/aerospike/logging/LoggingTests.java
Labels: enhancement

#819 FMWK-641 Clean up documentation
  src/main/asciidoc/index.adoc
  src/main/asciidoc/reference/configuration.adoc
  src/main/asciidoc/reference/transactions.adoc
  src/main/java/org/springframework/data/aerospike/query/FilterOperation.java
  src/main/java/org/springframework/data/aerospike/query/QueryEngine.java
  src/main/java/org/springframework/data/aerospike/query/ReactorQueryEngine.java
  src/main/java/org/springframework/data/aerospike/server/version/ServerVersionSupport.java
  src/test/java/org/springframework/data/aerospike/repository/query/blocking/delete/EqualsTests.java
  src/test/java/org/springframework/data/aerospike/sample/PersonRepository.java
  src/test/java/org/springframework/data/aerospike/transaction/reactive/ReactiveAerospikeTemplateTransactionTests.java
  src/test/java/org/springframework/data/aerospike/transaction/reactive/ReactiveAerospikeTemplateTransactionUnitTests.java
  src/test/java/org/springframework/data/aerospike/transaction/reactive/ReactiveAerospikeTransactionTestUtils.java
  src/test/java/org/springframework/data/aerospike/transaction/sync/AerospikeTemplateTransactionTests.java
  src/test/java/org/springframework/data/aerospike/transaction/sync/AerospikeTemplateTransactionUnitTests.java
  src/test/java/org/springframework/data/aerospike/transaction/sync/AerospikeTransactionalAnnotationTests.java
Labels: enhancement

#825 FMWK-647 Update dependencies
  pom.xml
  src/main/asciidoc/index.adoc
  src/main/asciidoc/reference/caching.adoc
  src/main/asciidoc/reference/configuration.adoc
  src/main/asciidoc/reference/transactions.adoc
Labels: dependencies

#826 FMWK-652 Set version to 5.0.0
  README.adoc
  pom.xml
Labels: dependencies, documentation

#827 FMWK-660 Update documentation
  .github/workflows/release.yml
  src/main/asciidoc/index.adoc
  src/main/asciidoc/reference/configuration.adoc
Labels: documentation

#828 FMWK-662 Format documentation
  src/main/asciidoc/index.adoc
  src/main/asciidoc/preface.adoc
  src/main/asciidoc/reference/aerospike-reactive-repositories.adoc
  src/main/asciidoc/reference/aerospike-repositories.adoc
  src/main/asciidoc/reference/caching.adoc
  src/main/asciidoc/reference/configuration.adoc
  src/main/asciidoc/reference/functionality.adoc
  src/main/asciidoc/reference/indexed-annotation.adoc
  src/main/asciidoc/reference/installation-and-usage.adoc
  src/main/asciidoc/reference/query-methods-collection.adoc
  src/main/asciidoc/reference/query-methods-combined.adoc
  src/main/asciidoc/reference/query-methods-id.adoc
  src/main/asciidoc/reference/query-methods-map.adoc
  src/main/asciidoc/reference/query-methods-modification.adoc
  src/main/asciidoc/reference/query-methods-pojo.adoc
  src/main/asciidoc/reference/query-methods-preface.adoc
  src/main/asciidoc/reference/query-methods-simple-property.adoc
  src/main/asciidoc/reference/secondary-indexes.adoc
  src/main/asciidoc/reference/template.adoc
  src/main/asciidoc/reference/tls.adoc
  src/main/asciidoc/reference/transactions.adoc
Labels: documentation
